In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [12]:
A = np.array([[2, 3, 4]
              , [10, 20, 30]])
B = np.array([[2, 3, 4]
              , [10, 20, 30]], dtype=np.float64)

print("Matrix A = \n", A)
print("Shape of A = ", A.shape)
print("Shape of A = ", A.dtype)

print("--------------------")

print("Matrix A = \n", B)
print("Shape of A = ", B.shape)
print("Shape of A = ", B.dtype)

Matrix A = 
 [[ 2  3  4]
 [10 20 30]]
Shape of A =  (2, 3)
Shape of A =  int64
--------------------
Matrix A = 
 [[ 2.  3.  4.]
 [10. 20. 30.]]
Shape of A =  (2, 3)
Shape of A =  float64


In [18]:
## Diagonal matrix
a = np.array([1, 2, 3, 4])

D_1 = np.diag(a)
print("D_1 = \n", D_1)

print("--------------------")

b = np.random.randint(1, 10, 5)
D_2 = np.diag(b)
print("D_2 = \n", D_2)

D_1 = 
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
--------------------
D_2 = 
 [[2 0 0 0 0]
 [0 3 0 0 0]
 [0 0 8 0 0]
 [0 0 0 5 0]
 [0 0 0 0 1]]


In [21]:
## identity matrix

I_3 = np.eye(3)
print("3 x 3 Identity = \n", I_3)

print("--------------------")

I_5 = np.eye(5)
print("5 x 5 Identity = \n", I_5)

3 x 3 Identity = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--------------------
5 x 5 Identity = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
## Transpose matrix

A = np.array([[1, 2, 3, 4]
              , [5, 6, 7, 8]], dtype = np.int64)

print("A = \n", A)
print("Transpose matrix A = \n", A.T)

A = 
 [[1 2 3 4]
 [5 6 7 8]]
Transpose matrix A = 
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [27]:
## matrix multiplication

A = np.array([[1, 2]
              , [3, 4]])
B = np.array([[1, 1]
              , [1, 2]])

print("A*B = \n", A*B)
print("A x B = \n", np.matmul(A, B))

A*B = 
 [[1 2]
 [3 8]]
A x B = 
 [[ 3  5]
 [ 7 11]]
